config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
  # 名前は必須入力かつ20文字以内
  validates :name , length: { maximum: 20 } , presence: true
  # 内容は必須入力かつ2文字以上30文字以下
  validates :body , length: { minimum: 2, maximum: 30 } , presence: true
  #年齢０以上の数字だけ入力できるようにする
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]   #同じコントローラ内のset_messageというメソッドを :edit,:updateのアクションの前に実行するように設定しています。
  def index
    @message = Message.new   # @message = Message.newで、Messageモデルのオブジェクトの初期化を行い、@messageに代入を行っている。
    #Meaageを全て取得する
    @messages = Message.all
  end
  def edit
  end
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
  #メッセージを作成する処理の流れは以下のようになっています。
  #先ほどのフォームに値を入力し送信ボタンを押すと /messagesというURLにPOSTでリクエストがパラメータと共に送信されます。その後、routes.rbで設定したMessagesControllerのcreateアクションが呼ばれます。
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def create
    @message = Message.new(message_params)
    if @message.save
    redirect_to root_path , notice: 'メッセージを保存しました。'
    else
      #メッセージが保存できなかった時は @messageのerrorsメソッドでエラーメッセージを取得することができます。
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"    #エラーメッセージをflash.now[:alert]に代入しています。
      render 'index'
    end
  end
  
  #nameと、bodyが含まれたパラメータ(message_params)を受け取り、 message_paramsの内容をもとにMessageモデルのインスタンスを生成(Message.new)し、変数@messageに代入しています。
  # ※ message_paramsについては次のストロングパラメータについての項で説明します。
  # @message.save でメッセージモデルのインスタンスをデータベースに保存しています。
  # ルートURLにリダイレクトしています。
  
  private
  def message_params
    params.require(:message).permit(:name, :age, :body)
    #def message_paramsはparamsに:messageというキーが存在するか検証し、存在する場合はparams[:message]のうち、キーが:nameと:bodyの値のみ受け取るようにフィルタリングを行っています
  end
  ## ここまで
  # ブラウザのフォームから送信されたパラメータは、コントローラ側からは params で取得できます。
  def set_message
    @message = Message.find(params[:id])
  end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
    </div>
  </nav>
  <div class="container">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, html: {class: "form-horizontal"}) do |f| %>
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="message_name" class="col-sm-1 control-label">名前</label>
    <div class="col-sm-6">
        <%= f.text_field :name, size: 40, maxlength: 30, class: "form-control" , :placeholder =>"名前を記入してください。"%>
    </div>
    <div class="col-sm-4"></div>
  </div>
  
  <div class="form-group">
    <label for="message_age" class="col-sm-1 control-label">年齢</label>
    <div class="col-sm-6">
        <%= f.text_field :age, size: 40, maxlength: 30, class: "form-control" , :placeholder =>"年齢を記入してください。"%>
    </div>
    <div class="col-sm-4"></div>
  </div>
  
  <div class="form-group">
    <label for="message_body" class="col-sm-1 control-label">内容</label>
    <div class="col-sm-10">
      <%= f.text_area :body, :class => "form-control message_textarea", :placeholder =>"メッセージを記入してください。" %>       <!--placeholder =>"メッセージを記入してください。"-->
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <%= f.submit class: "btn btn-sm btn-primary" %>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    メッセージ一覧
  </div>
    
  <div class="panel-body">
    <% @messages.each do |message| %>
      <span class="label label-info">名前：<%= message.name %>さん  </span>
      年齢：<%= message.age %>歳   内容：<%= message.body %>
        (<%= link_to "edit" , edit_message_path(message) %>    <!-- #メッセージ一覧画面の右側に編集ページへのリンクを配置します。link_toの第一引数はラベルになり、
        edit_message_path(message)の部分では、編集ページへのパスを指定しています。-->
        <%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>)
      <br>
    <% end %>
  </div>
</div>

<%= render 'form' %>